### PR TITLE
Support for automatic mode in color selection buttons

### LINKED ISSUE #172: Handle no color selection for text & background color
By default, colors of background & text change based on the current brightness of the app.
When selecting another color, there is no way to restore the default dynamic colors

Add a button to restore default dynamic colors; `Automatic` for text color & `No color` for background color

### PR DESCRIPTION
**Pull request by amantoux**
Closes #172

### CODE REVIEW

**Review by Amir-P — DISMISSED** [review]
I think "No Color" or "Transparent" or "Remove background color" is a better term than "Automatic" since that's what really happening. WDYT?

**Comment by amantoux** [comment]
> I think "No Color" or "Transparent" or "Remove background color" is a better term than "Automatic" since that's what really happening. WDYT?

I used MS Word wording. I believe the rational behind this is that the color automatically shifts from light mode color to dark mode color. Other possibilities not not have dynamic colors

image

**Comment by amantoux** [comment]
Changed accordingly ✅

**Review by Amir-P — APPROVED** [review]
LGTM.

**Pull request merged**
