### PR TITLE
[Fleather] Support for background color

### PR DESCRIPTION
**Pull request by amantoux**
This is the first part of a couple of PRs (the first [one](https://github.com/fleather-editor/fleather/pull/21) is related to Parchment)
Simply adapts the text style with the appropriate background color.

***NB**: this won't build successfully as it has a dependency on Parchment*
***NB**: no toolbar item to pick a color in the PR, this will be part of a later PR*

### CODE REVIEW

**Review by Amir-P — COMMENTED** [review]
Should we rebase first to see the green light and then merge? @amantoux

**Comment by amantoux** [comment]
> Should we rebase first to see the green light and then merge? @amantoux 

Yes @Amir-P 
But it needs Parchment to be published on pub.dev

**Comment by Amir-P** [comment]
> > Should we rebase first to see the green light and then merge? @amantoux
> 
> Yes @Amir-P But it needs Parchment to be published on pub.dev

As far as I can remember we depend on local Parchment in Fleather, don't we? @amantoux

**Comment by amantoux** [comment]
> > > Should we rebase first to see the green light and then merge? @amantoux
> 
> > 
> 
> > Yes @Amir-P But it needs Parchment to be published on pub.dev
> 
> 
> 
> As far as I can remember we depend on local Parchment in Fleather, don't we? @amantoux 

True, I thought we wanted to change that (?)

**Pull request closed without merging**
