### PR TITLE
GitHub actions

### PR DESCRIPTION
**Pull request by amantoux**

### CODE REVIEW

**Review by Amir-P — COMMENTED** [review]
Why are we using a single job called build including analyzing and checking format? Isn't it better to have different job for each one? @amantoux

**Comment by amantoux** [comment]
> Why are we using a single job called build including analyzing and checking format? Isn't it better to have different job for each one? @amantoux 

The install of Java & Flutter is quite long (circa 50s)
(Only reason on my end)

**Review by Amir-P — COMMENTED** [review]
I think we can get rid of Java since we're not building for Android. Also since we're not building anything it would be more appropriate to use another name instead of build for the job. @amantoux

**Review by Amir-P — APPROVED** [review]
LGTM.

**Pull request merged**
