### PR TITLE
Review checkbox design

### PR DESCRIPTION
**Pull request by amantoux**
Increase size of checkbox as they are difficult to handle on small devices and review design

### CODE REVIEW

**Comment by amantoux** [comment]
@Amir-P can you take a look?

**Comment by amantoux** [comment]
@Amir-P simply changed the size of the check box. Tell me if it suits better
Will work on redesign in parallel

**Comment by Amir-P** [comment]
> @Amir-P simply changed the size of the check box. Tell me if it suits better
> Will work on redesign in parallel

Can we use the `Checkbox` from Flutter widgets instead of this custom widget? @amantoux

**Comment by Amir-P** [comment]
It's still small and I guess 24 would be better on touch devices. @amantoux  
https://material.io/components/checkboxes#specs

**Review by Amir-P — CHANGES_REQUESTED** [review]
It's still small and I guess 24 would be better on touch devices. @amantoux  
https://material.io/components/checkboxes#specs

**Comment by amantoux** [comment]
24 is huge, or else implies the line height at least 24 which sounds too much

Try look at this comment in Github mobile app

- [ ] test

**Comment by Amir-P** [comment]
> 24 is huge, or else implies the line height at least 24 which sounds too much @amantoux
> 
> Try look at this comment in Github mobile app
> 
> * [ ]  test

You're right. Let's go with 16. @amantoux

**Comment by amantoux** [comment]
Ok finally no possible customization possible in terms of size on `Checkbox`

**Review by Amir-P — APPROVED** [review]
The size is good I think and no need for customization. LGTM.

**Pull request merged**
