### PR TITLE
Fix/heading 6 TextBlockTheme not getting applied 

### LINKED ISSUE #312: Heading 6 TextBlockTheme is not applied.
I noticed a bug in the FleatherThemeData where the TextBlockTheme for Heading 6 is not applied to the text. 

To reproduce: Try to set it with the color red: 

Heading 6 is set to be red.
image
In the selection, it is not red. Neither is it in the editor when set.
image

### PR DESCRIPTION
**Pull request by Kontrano**
Closes #312 

Adding this line fixed the TextBlockTheme not getting applied.

### CODE REVIEW

**Comment by Amir-P** [comment]
Thanks for contributing! Are you willing to add the tests for 'merge' function so that it doesn't happen in the future? @Kontrano

**Comment by Kontrano** [comment]
Eh sure I'll give it a try, Never really wrote tests before so ill try my best

**Review by Amir-P — CHANGES_REQUESTED** [review]
Thanks @Kontrano, the test looks good for the change you've made. We are almost done. The code just needs to be formatted with `dart format`.

**Comment by Kontrano** [comment]
Hi @Amir-P I've run the command on the file so it should be ready right?

**Comment by Amir-P** [comment]
Sorry but `editor_toolbar.dart` is not correctly formatted. 😀 You can just do `dart format .` in the repository root directory to format everything. @Kontrano

**Comment by Kontrano** [comment]
@Amir-P  Oops xD, Ran it again should be good now. Thanks for the tip to format everything.

**Review by Amir-P — APPROVED** [review]
LGTM. Thanks for contributing! @Kontrano 

@amantoux Do you wanna have a look, too?

**Comment by amantoux** [comment]
> LGTM. Thanks for contributing! @Kontrano
> 
> @amantoux Do you wanna have a look, too?

Yes good to me too. Thanks again @Kontrano

**Pull request merged**
