### PR TITLE
Adapt to Flutter 3.16 API changes

### LINKED ISSUE #173: Flutter 3.16
Adapt Fleather to Flutter 3.16 API changes

### PR DESCRIPTION
**Pull request by amantoux**
Closes #173

### CODE REVIEW

**Comment by amantoux** [comment]
Tests fail to https://github.com/flutter/flutter/issues/138709

**Comment by Amir-P** [comment]
Could you take a look at this now Alan? I can't request a review from you since you're the creator. @amantoux

**Comment by amantoux** [comment]
LGTM, will add removal of deprecated `textScaleFactor`

**Review by Amir-P — APPROVED** [review]
LGTM.

**Pull request merged**
