### PR TITLE
Move cursor at the end of pasted text after pasting (#271)

### PR DESCRIPTION
**Pull request by jacquetc**
Hello,

See #271 for more information.

I have to adapt the test

### CODE REVIEW

**Comment by jacquetc** [comment]
Test was well written. The culprit was my code not taking into account the case delta or plain text.
Example runs ok, tests runs ok.

**Comment by jacquetc** [comment]
just formatted the file

**Review by amantoux — CHANGES_REQUESTED** [review]
Thank you for this PR!
Do you mind adding a test to ensure this doens't break?

**Comment by jacquetc** [comment]
You are welcome. I can try to write a dedicated test, ensuring that there is no selection and that pasting while something is selected. I'm new to Dart, so feel free to comment. 

On another note, the mean of fleather to change the posisition & selection feels a bit strange to me. Knowing well QTextDocument/QTextEdit, I was looking for things like setPosition(position, keepAnchor) or alternatives.  Here, I add to use userUpdateTextEditingValue to change the cursor position & selection. Maybe that it's not Fleather/Flutter philosophy, but I was looking for more programmatic ways to handle the cursor. Couldn't it be a possible enhancement to offer a similar API for text cursor movement ? To have a better idea: [QTextEdit::moveCursor(...)](https://doc.qt.io/qt-6/qtextedit.html#moveCursor) and [QTextCursor::setPosition(...)](https://doc.qt.io/qt-6/qtextcursor.html#setPosition) . If you are interested for me to implement it, we can move this discussion in a proper "enhancement" issue.

**Comment by jacquetc** [comment]
Test written

**Comment by jacquetc** [comment]
Tested successfully on Linux, Windows and Web. Web didn't have the problem to begin with, my patch didn't break that at least ;-)

**Review by amantoux — APPROVED** [review]
LGTM
Thanks!

**Comment by amantoux** [comment]
> You are welcome. I can try to write a dedicated test, ensuring that there is no selection and that pasting while something is selected. I'm new to Dart, so feel free to comment.
> 
> On another note, the mean of fleather to change the posisition & selection feels a bit strange to me. Knowing well QTextDocument/QTextEdit, I was looking for things like setPosition(position, keepAnchor) or alternatives. Here, I add to use userUpdateTextEditingValue to change the cursor position & selection. Maybe that it's not Fleather/Flutter philosophy, but I was looking for more programmatic ways to handle the cursor. Couldn't it be a possible enhancement to offer a similar API for text cursor movement ? To have a better idea: [QTextEdit::moveCursor(...)](https://doc.qt.io/qt-6/qtextedit.html#moveCursor) and [QTextCursor::setPosition(...)](https://doc.qt.io/qt-6/qtextcursor.html#setPosition) . If you are interested for me to implement it, we can move this discussion in a proper "enhancement" issue.

Interesting. We try to leverage as much as possible Flutter concepts. The `TextEditingValue` contains selection, composing range and text value and serves as DTO to communicate with systems IME.
We want to stick as much as possible to Flutter's concepts to benefit from the work done in the framework on various complexities related to text editing (native selection tools, RTL, etc...)

**Comment by jacquetc** [comment]
> > You are welcome. I can try to write a dedicated test, ensuring that there is no selection and that pasting while something is selected. I'm new to Dart, so feel free to comment.
> > On another note, the mean of fleather to change the posisition & selection feels a bit strange to me. Knowing well QTextDocument/QTextEdit, I was looking for things like setPosition(position, keepAnchor) or alternatives. Here, I add to use userUpdateTextEditingValue to change the cursor position & selection. Maybe that it's not Fleather/Flutter philosophy, but I was looking for more programmatic ways to handle the cursor. Couldn't it be a possible enhancement to offer a similar API for text cursor movement ? To have a better idea: [QTextEdit::moveCursor(...)](https://doc.qt.io/qt-6/qtextedit.html#moveCursor) and [QTextCursor::setPosition(...)](https://doc.qt.io/qt-6/qtextcursor.html#setPosition) . If you are interested for me to implement it, we can move this discussion in a proper "enhancement" issue.
> 
> Interesting. We try to leverage as much as possible Flutter concepts. The `TextEditingValue` contains selection, composing range and text value and serves as DTO to communicate with systems IME. We want to stick as much as possible to Flutter's concepts to benefit from the work done in the framework on various complexities related to text editing (native selection tools, RTL, etc...)

Thank you, I'm still wrapping my head around Flutter approach. It could be an enhancement for the internals of Fleather, but not much since TextEditingValue does the same job. The "move" on the other hand could benefit the testing and implementation of common text navigation shortcuts like : Ctrl+Arrow Left/Right, Ctrl+Home/End, etc... 

Actually, "move" would be less useful internally than a "int determinePositionFor(int referencePosition, MoveOperation operation)" See [MoveOperation](https://doc.qt.io/qt-6/qtextcursor.html#MoveOperation-enum). What do you think ?

**Pull request merged**
