### PR TITLE
Add additionalFormats to fallback and make formats public

### PR DESCRIPTION
**Pull request by Amir-P**
Based on #372.

Made current auto formats public for users to be able to cherrypick.

### CODE REVIEW

**Review by amantoux — APPROVED** [review]
LGTM
I guess the natice autoformats are made public to allow users to cherrypick
It would be nice to add a comment in the PR (to avoid guessing the reason :))

**Review by amantoux — CHANGES_REQUESTED** [review]
Maybe add test?

**Comment by Amir-P** [comment]
> Maybe add test?

I found it unnecessary, but if you think it's needed I can add the test too. @amantoux

**Comment by amantoux** [comment]
> > Maybe add test?
> 
> I found it unnecessary, but if you think it's needed I can add the test too. @amantoux

If not too long to write, I think it is worth

**Review by amantoux — COMMENTED** [review]
LGTM

**Review by amantoux — APPROVED** [review]

**Pull request merged**
