### PR TITLE
[Fleather] Support for background color

### PR DESCRIPTION
**Pull request by amantoux**

### CODE REVIEW

**Review by Amir-P — APPROVED** [review]
LGTM.

**Comment by MohammedSalehelShazly** [comment]
Good job
but how can I use it?
@Amir-P 
@amantoux

**Comment by amantoux** [comment]
It can only be set programmatically for the time being.
use 
``` dart
Delta()..insert('With background', 'bg': Color::value)
```

**Comment by MohammedSalehelShazly** [comment]
thanks It's run with me 
```
ctrl.formatText(
	index,
	length,
	ParchmentAttribute.backgroundColor.withValue(clr)
)
```

**Pull request merged**
