### PR TITLE
Increase test coverage of editor toolbar

### PR DESCRIPTION
**Pull request by amantoux**
Test coverage is poor on editor toolbar.
This PR aims at testing in code the basic functionalities of the toolbar
(also testing checking a checkbox)

### CODE REVIEW

**Comment by amantoux** [comment]
@Amir-P  Can you please review?

Thanks

**Comment by Amir-P** [comment]
Hey Alan, I have some free time tonight. Will review #127 and #128 . @amantoux

**Comment by amantoux** [comment]
> Hey Alan, I have some free time tonight. Will review both #127 and #128 . @amantoux

Thanks @Amir-P 

I'm preparing a third one 😀

**Review by Amir-P — APPROVED** [review]
LGTM

**Pull request merged**
