### PR TITLE
Fix wrong toolbar positioning

### LINKED ISSUE #96: Selection toolbar wrong positioning
## Steps to Reproduce

1. Run the example app
2. Select the heading text ("Fleather")
3. Instead of displaying it right above or under the selected text, it appears way below it.

### PR DESCRIPTION
**Pull request by Amir-P**
Fixes #96 using Flutter's `TextSelectionToolbarAnchors` to compute contextMenuAnchors.

### CODE REVIEW

**Review by amantoux — COMMENTED** [review]
neater! Do you think we could detect such issues in some tests?

**Comment by Amir-P** [comment]
> @Amir-P Neater! Do you think we could detect such issues in some tests?

I'm not expert in widget testing (yet!) and not sure how the tests might look like for this. Do you have anything in mind? @amantoux

**Comment by Amir-P** [comment]
I think the only way to validate toolbar positioning is using golden tests which is a bit tricky to get it work correctly since there are differences in text rendering on different platforms and generated files on my machine (macOS) is not the same as the ones generated in our CI pipeline (Linux). I think we can skip the tests for this for now. WDYT? @amantoux

**Comment by amantoux** [comment]
> I think the only way to validate toolbar positioning is using golden tests which is a bit tricky to get it work correctly since there are differences in text rendering on different platforms and generated files on my machine (macOS) is not the same as the ones generated in our CI pipeline (Linux). I think we can skip the tests for this for now. WDYT? @amantoux

Ok then, let's merge this

**Pull request merged**
